module.exports = function(grunt){
  grunt.initConfig({
    watch:{
      options:{
        livereload:460
      },
      php:{
        files:['**/*.php'],
        reload:true
      },
      sass:{
        files:['sass/*.scss'],
        tasks:['sass']
      },
      css:{
        files:['css/*.css'],
        reload:true
      },
      sass_admin:{
        files:['admin/sass/*.scss'],
        tasks:['sass']
      },
      css_admin:{
        files:['admin/css/*.css'],
        reload:true
      },
      js_min:{
        files:['js/script.js'],
        tasks:['uglify']
      },
      js:{
        files:['js/script.min.js'],
        reload:true
      },
      js_min_admin:{
        files:['admin/js/script.js'],
        tasks:['uglify']
      },
      js_admin:{
        files:['admin/js/script.min.js'],
        reload:true
      }
    },
    uglify:{
      target:{
        files:{
          'js/script.min.js':'js/script.js',
          'admin/js/script.min.js':'admin/js/script.js'
        }
      }
    },
    sass:{
      dist:{
        options:{
          style:'compressed'
        },
        files:{
          'css/style.css':'sass/style.scss',
          'admin/css/style.css':'admin/sass/style.scss'
        },
      },
    },
    clean:{
        build:{
          src:'dist'
        }
    },
    copy:{
      main:{
          expand:true,
          src:['admin/**','build/**','css/**','js/**','vendor/**','aqua_bar.php'],
          dest:'dist'
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-uglify');

  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-clean');

  grunt.registerTask('default',['watch']); // Para desenvolvimento!
  grunt.registerTask('gerarApp',['clean','copy']); // Para produção!
}
