module.exports = function(grunt){
  grunt.initConfig({
    watch:{
      options:{
        livereload:460
      },
      php:{
        files:['**/*.php'],
        reload:true
      },
      sass:{
        files:['sass/*.scss'],
        tasks:['sass']
      },
      css:{
        files:['css/*.css'],
        reload:true
      },
      js_min:{
        files:['js/script.js'],
        tasks:['uglify']
      },
      js:{
        files:['js/script.min.js'],
        reload:true
      }
    },
    uglify:{
      target:{
        files:{
          'js/script.min.js':'js/script.js'
        }
      }
    },
    sass:{
      dist:{
        options:{
          style:'compressed'
        }
      },
      files:{
        'css/style.css':'sass/style.scss'
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-uglify');

  grunt.registerTask('default',['watch']);
}
